"""PDF exporter - generates dataset card PDF."""

from __future__ import annotations

from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.lib import colors

from automl_synth.types import GeneratedRow, QualityReport, ResearchReport


def export_pdf(
    rows: list[GeneratedRow],
    research: ResearchReport,
    quality: QualityReport,
    output_path: str,
) -> str:
    """Generate a PDF dataset card."""
    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        rightMargin=72,
        leftMargin=72,
        topMargin=72,
        bottomMargin=72,
    )
    styles = getSampleStyleSheet()
    story = []

    title_style = styles["Title"]
    title_style.fontSize = 24
    story.append(Paragraph("Dataset Card", title_style))
    story.append(Spacer(1, 12))

    heading_style = styles["Heading2"]
    normal_style = styles["Normal"]

    story.append(Paragraph("Overview", heading_style))
    story.append(Paragraph(f"<b>Topic:</b> {research.topic}", normal_style))
    story.append(Paragraph(f"<b>Total Rows:</b> {quality.total_rows}", normal_style))
    story.append(Paragraph(f"<b>Labels:</b> {', '.join(research.labels)}", normal_style))
    story.append(Paragraph(f"<b>Quality Score:</b> {quality.quality_score}/100 ({quality.quality_grade})", normal_style))
    story.append(Spacer(1, 12))

    story.append(Paragraph("Label Distribution", heading_style))
    label_data = [["Label", "Count"]]
    for label, count in quality.label_distribution.items():
        label_data.append([label, str(count)])
    table = Table(label_data, colWidths=[3 * inch, 2 * inch])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.grey),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 12),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 12),
        ("BACKGROUND", (0, 1), (-1, -1), colors.beige),
        ("GRID", (0, 0), (-1, -1), 1, colors.black),
    ]))
    story.append(table)
    story.append(Spacer(1, 12))

    story.append(Paragraph("Quality Metrics", heading_style))
    story.append(Paragraph(f"<b>Class Balance Ratio:</b> {quality.class_balance_ratio}", normal_style))
    story.append(Paragraph(f"<b>Duplicate Rows:</b> {quality.duplicate_rows}", normal_style))
    story.append(Paragraph(f"<b>Avg Text Length:</b> {quality.avg_text_length} chars", normal_style))
    story.append(Paragraph(f"<b>Avg Word Count:</b> {quality.avg_word_count}", normal_style))
    story.append(Paragraph(f"<b>Vocabulary Diversity:</b> {quality.unique_vocabulary_ratio:.1%}", normal_style))
    story.append(Spacer(1, 12))

    if quality.warnings:
        story.append(Paragraph("Warnings", heading_style))
        for w in quality.warnings:
            story.append(Paragraph(f"- {w}", normal_style))
        story.append(Spacer(1, 12))

    story.append(Paragraph("Sample Rows", heading_style))
    sample_data = [["ID", "Text", "Label", "Difficulty"]]
    for row in rows[:10]:
        text_preview = row.text[:100] + ("..." if len(row.text) > 100 else "")
        sample_data.append([str(row.id), text_preview, row.label, row.difficulty])
    sample_table = Table(sample_data, colWidths=[0.5 * inch, 3.5 * inch, 1.2 * inch, 1 * inch])
    sample_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.grey),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
        ("ALIGN", (0, 0), (-1, -1), "LEFT"),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 10),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 12),
        ("BACKGROUND", (0, 1), (-1, -1), colors.beige),
        ("GRID", (0, 0), (-1, -1), 1, colors.black),
        ("FONTSIZE", (0, 1), (-1, -1), 9),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    story.append(sample_table)

    story.append(Spacer(1, 24))
    story.append(Paragraph(
        "<i>This dataset is synthetically generated by AutoML-Synth. "
        "Quality metrics are automated estimates and should be validated for production use.</i>",
        styles["Italic"],
    ))

    doc.build(story)
    return output_path
